import { TarotCard } from './tarotCards';

export const minorArcanaWands: TarotCard[] = [
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    keywords: ['inspiration', 'new opportunities', 'growth', 'potential'],
    uprightMeaning: 'Inspiration, new opportunities, growth, potential, new venture',
    reversedMeaning: 'Lack of energy, lack of passion, boredom, delays',
    description: 'A new creative spark, the beginning of a passionate journey',
    element: 'Fire'
  },
  {
    id: 'two-of-wands',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    keywords: ['planning', 'making decisions', 'leaving comfort zone', 'discovery'],
    uprightMeaning: 'Planning, making decisions, leaving comfort zone, discovery',
    reversedMeaning: 'Fear of change, playing it safe, bad planning, lack of planning',
    description: 'Planning the next move, considering options',
    element: 'Fire'
  },
  {
    id: 'three-of-wands',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    keywords: ['expansion', 'foresight', 'overseas opportunities', 'long-term success'],
    uprightMeaning: 'Expansion, foresight, overseas opportunities, long-term success',
    reversedMeaning: 'Playing small, lack of foresight, unexpected delays',
    description: 'Looking ahead to future opportunities and expansion',
    element: 'Fire'
  },
  {
    id: 'four-of-wands',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    keywords: ['celebration', 'joy', 'harmony', 'relaxation', 'homecoming'],
    uprightMeaning: 'Celebration, joy, harmony, relaxation, homecoming',
    reversedMeaning: 'Lack of support, transience, home conflicts, feeling unwelcome',
    description: 'Celebration and harmony, enjoying the fruits of labor',
    element: 'Fire'
  },
  {
    id: 'five-of-wands',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    keywords: ['competition', 'conflict', 'tension', 'diversity'],
    uprightMeaning: 'Competition, rivalries, conflict, tension, diversity',
    reversedMeaning: 'Avoiding conflict, respecting differences, finding common ground',
    description: 'Competitive energy and conflicting interests',
    element: 'Fire'
  },
  {
    id: 'six-of-wands',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    keywords: ['victory', 'success', 'recognition', 'progress'],
    uprightMeaning: 'Victory, success, public recognition, progress, self-confidence',
    reversedMeaning: 'Private achievement, personal definition of success, fall from grace',
    description: 'Victory and public recognition for achievements',
    element: 'Fire'
  },
  {
    id: 'seven-of-wands',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    keywords: ['perseverance', 'defensive', 'maintaining control', 'challenge'],
    uprightMeaning: 'Challenge, perseverance, defense, maintaining control',
    reversedMeaning: 'Giving up, overwhelmed, exhausted, admitting defeat',
    description: 'Standing your ground against opposition',
    element: 'Fire'
  },
  {
    id: 'eight-of-wands',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    keywords: ['movement', 'speed', 'progress', 'quick decisions', 'air travel'],
    uprightMeaning: 'Movement, fast paced change, action, alignment, air travel',
    reversedMeaning: 'Delays, frustration, holding off, internal alignment',
    description: 'Swift movement and rapid progress toward goals',
    element: 'Fire'
  },
  {
    id: 'nine-of-wands',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    keywords: ['resilience', 'courage', 'persistence', 'boundaries'],
    uprightMeaning: 'Resilience, courage, persistence, test of faith, boundaries',
    reversedMeaning: 'Exhaustion, giving up, overwhelmed, paranoia',
    description: "Last stand, protecting what you've built",
    element: 'Fire'
  },
  {
    id: 'ten-of-wands',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    keywords: ['burden', 'responsibility', 'hard work', 'completion'],
    uprightMeaning: 'Burden, extra responsibility, hard work, completion',
    reversedMeaning: 'Inability to delegate, overstressed, resigned to fate',
    description: 'Carrying a heavy burden, nearing completion',
    element: 'Fire'
  },
  {
    id: 'page-of-wands',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    keywords: ['exploration', 'excitement', 'freedom', 'adventure'],
    uprightMeaning: 'Exploration, excitement, freedom, adventure, new ideas',
    reversedMeaning: 'Lack of direction, procrastination, creating conflict',
    description: 'Enthusiastic messenger bringing creative opportunities',
    element: 'Fire'
  },
  {
    id: 'knight-of-wands',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    keywords: ['action', 'adventure', 'fearlessness', 'impulsiveness'],
    uprightMeaning: 'Action, adventure, fearlessness, high energy, impulsiveness',
    reversedMeaning: 'Anger, impulsiveness, recklessness, arrogance',
    description: 'Passionate pursuit of goals and adventures',
    element: 'Fire'
  },
  {
    id: 'queen-of-wands',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    keywords: ['confidence', 'independence', 'determination', 'charisma'],
    uprightMeaning: 'Confidence, independence, charisma, determination',
    reversedMeaning: 'Self-respect, self-confidence, introverted, jealousy',
    description: 'Confident and charismatic leadership',
    element: 'Fire'
  },
  {
    id: 'king-of-wands',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    keywords: ['leadership', 'vision', 'entrepreneur', 'honor'],
    uprightMeaning: 'Natural leader, vision, entrepreneur, honor',
    reversedMeaning: 'Impulsiveness, haste, ruthless, high expectations',
    description: 'Visionary leadership and entrepreneurial spirit',
    element: 'Fire'
  }
];

export const minorArcanaCups: TarotCard[] = [
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    keywords: ['love', 'new relationships', 'compassion', 'creativity'],
    uprightMeaning: 'Love, new relationships, compassion, creativity, emotional new beginnings',
    reversedMeaning: 'Self-love, intuition, repressed emotions, emotional loss',
    description: 'New emotional beginning, overflowing feelings',
    element: 'Water'
  },
  {
    id: 'two-of-cups',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    keywords: ['unity', 'partnership', 'connection', 'attraction'],
    uprightMeaning: 'Unity, partnership, mutual attraction, connection',
    reversedMeaning: 'Imbalance, broken communication, tension, separation',
    description: 'Partnership and mutual connection',
    element: 'Water'
  },
  {
    id: 'three-of-cups',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    keywords: ['celebration', 'friendship', 'community', 'gatherings'],
    uprightMeaning: 'Celebration, friendship, creativity, community, happy gatherings',
    reversedMeaning: 'Independence, alone time, hardcore partying, three\'s a crowd',
    description: 'Celebration with friends and community',
    element: 'Water'
  },
  {
    id: 'four-of-cups',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    keywords: ['apathy', 'contemplation', 'disconnection', 'melancholy'],
    uprightMeaning: 'Apathy, contemplation, disconnection, melancholy, boredom',
    reversedMeaning: 'Sudden awareness, choosing happiness, acceptance, moving on',
    description: 'Contemplation and emotional withdrawal',
    element: 'Water'
  },
  {
    id: 'five-of-cups',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    keywords: ['loss', 'grief', 'disappointment', 'regret'],
    uprightMeaning: 'Loss, grief, disappointment, regret, despair, bereavement',
    reversedMeaning: 'Moving on, acceptance, finding peace, forgiveness',
    description: 'Grief and focusing on loss',
    element: 'Water'
  },
  {
    id: 'six-of-cups',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    keywords: ['nostalgia', 'childhood', 'innocence', 'joy'],
    uprightMeaning: 'Nostalgia, childhood memories, innocence, joy, generosity',
    reversedMeaning: 'Living in the past, forgiveness, lacking playfulness',
    description: 'Nostalgia and reconnecting with the past',
    element: 'Water'
  },
  {
    id: 'seven-of-cups',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    keywords: ['choices', 'illusions', 'wishful thinking', 'imagination'],
    uprightMeaning: 'Choices, searching for purpose, illusion, wishful thinking',
    reversedMeaning: 'Lack of purpose, diversion, confusion, clarity, making choices',
    description: 'Many choices and possibilities, some illusory',
    element: 'Water'
  },
  {
    id: 'eight-of-cups',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    keywords: ['abandonment', 'walking away', 'letting go', 'searching'],
    uprightMeaning: 'Walking away, disillusionment, leaving behind, withdrawal',
    reversedMeaning: 'Trying one more time, indecision, aimless drifting',
    description: 'Walking away from what no longer serves',
    element: 'Water'
  },
  {
    id: 'nine-of-cups',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    keywords: ['satisfaction', 'emotional fulfillment', 'wishes coming true'],
    uprightMeaning: 'Emotional fulfillment, satisfaction, happiness, wishes coming true',
    reversedMeaning: 'Inner happiness, materialism, dissatisfaction, greed',
    description: 'Emotional satisfaction and contentment',
    element: 'Water'
  },
  {
    id: 'ten-of-cups',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    keywords: ['harmony', 'happiness', 'family', 'emotional fulfillment'],
    uprightMeaning: 'Harmony, happiness, alignment, family bliss',
    reversedMeaning: 'Misalignment of values, broken home, neglect',
    description: 'Complete emotional fulfillment and family harmony',
    element: 'Water'
  },
  {
    id: 'page-of-cups',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    keywords: ['creative opportunities', 'intuition', 'curiosity', 'messages'],
    uprightMeaning: 'Creative opportunities, intuitive messages, curiosity, possibility',
    reversedMeaning: 'Emotional immaturity, insecurity, creative blocks',
    description: 'Creative and intuitive messages arriving',
    element: 'Water'
  },
  {
    id: 'knight-of-cups',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    keywords: ['romance', 'charm', 'imagination', 'beauty'],
    uprightMeaning: 'Romance, charm, beauty, imagination, creativity',
    reversedMeaning: 'Moodiness, disappointment, over-imagination, jealousy',
    description: 'Romantic proposals and creative pursuits',
    element: 'Water'
  },
  {
    id: 'queen-of-cups',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    keywords: ['compassion', 'intuition', 'calm', 'healing'],
    uprightMeaning: 'Compassionate, caring, intuitive, in flow with emotions',
    reversedMeaning: 'Inner feelings, self-care, self-love, codependency',
    description: 'Emotional intelligence and nurturing presence',
    element: 'Water'
  },
  {
    id: 'king-of-cups',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    keywords: ['emotional balance', 'compassion', 'diplomacy', 'wisdom'],
    uprightMeaning: 'Emotional balance, compassion, diplomacy, wisdom',
    reversedMeaning: 'Coldness, moodiness, emotional manipulation, volatility',
    description: 'Mastery over emotions with compassion',
    element: 'Water'
  }
];

export const minorArcanaSwords: TarotCard[] = [
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    keywords: ['breakthrough', 'clarity', 'sharp mind', 'new ideas'],
    uprightMeaning: 'Breakthrough, clarity, sharp mind, new ideas, mental clarity',
    reversedMeaning: 'Confusion, chaos, lack of clarity, brutality',
    description: 'Mental breakthrough and clear communication',
    element: 'Air'
  },
  {
    id: 'two-of-swords',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    keywords: ['indecision', 'choices', 'truce', 'blocked emotions'],
    uprightMeaning: 'Indecision, choices, truce, stalemate, blocked emotions',
    reversedMeaning: 'Lesser of two evils, no right choice, confusion, information overload',
    description: 'Difficult decision requiring careful thought',
    element: 'Air'
  },
  {
    id: 'three-of-swords',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    keywords: ['heartbreak', 'sorrow', 'grief', 'hurt'],
    uprightMeaning: 'Heartbreak, emotional pain, sorrow, grief, hurt',
    reversedMeaning: 'Recovery, forgiveness, moving on, releasing pain',
    description: 'Heartbreak and emotional pain',
    element: 'Air'
  },
  {
    id: 'four-of-swords',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    keywords: ['rest', 'restoration', 'contemplation', 'recuperation'],
    uprightMeaning: 'Rest, restoration, contemplation, recuperation, passive waiting',
    reversedMeaning: 'Restlessness, burnout, stress, lack of progress',
    description: 'Rest and mental restoration',
    element: 'Air'
  },
  {
    id: 'five-of-swords',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    keywords: ['conflict', 'defeat', 'winning at all costs', 'betrayal'],
    uprightMeaning: 'Conflict, disagreements, competition, defeat, winning at all costs',
    reversedMeaning: 'Reconciliation, making amends, past resentment',
    description: 'Conflict and pyrrhic victory',
    element: 'Air'
  },
  {
    id: 'six-of-swords',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    keywords: ['transition', 'leaving', 'moving on', 'recovery'],
    uprightMeaning: 'Transition, leaving behind, moving on, recovery, spirit guides',
    reversedMeaning: 'Cannot move on, carrying baggage, resisting transition',
    description: 'Moving toward calmer waters',
    element: 'Air'
  },
  {
    id: 'seven-of-swords',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    keywords: ['deception', 'strategy', 'sneakiness', 'betrayal'],
    uprightMeaning: 'Deception, betrayal, acting strategically, sneakiness',
    reversedMeaning: 'Coming clean, rethinking approach, deception revealed',
    description: 'Strategic thinking or deceptive behavior',
    element: 'Air'
  },
  {
    id: 'eight-of-swords',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    keywords: ['restriction', 'imprisonment', 'victim mentality', 'trapped'],
    uprightMeaning: 'Restriction, imprisonment, victim mentality, trapped, powerlessness',
    reversedMeaning: 'Self-acceptance, new perspective, freedom, release',
    description: 'Feeling trapped by mental restrictions',
    element: 'Air'
  },
  {
    id: 'nine-of-swords',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    keywords: ['anxiety', 'worry', 'fear', 'nightmares'],
    uprightMeaning: 'Anxiety, worry, fear, depression, nightmares, negative thoughts',
    reversedMeaning: 'Hope, reaching out, positive thoughts, overcoming fear',
    description: 'Anxiety and mental anguish',
    element: 'Air'
  },
  {
    id: 'ten-of-swords',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    keywords: ['endings', 'loss', 'betrayal', 'rock bottom'],
    uprightMeaning: 'Painful endings, deep wounds, betrayal, loss, crisis, rock bottom',
    reversedMeaning: 'Recovery, regeneration, resisting an ending, rising above',
    description: 'Painful ending and rock bottom',
    element: 'Air'
  },
  {
    id: 'page-of-swords',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    keywords: ['curiosity', 'restlessness', 'mental energy', 'communication'],
    uprightMeaning: 'Curiosity, restlessness, mental energy, communication, new ideas',
    reversedMeaning: 'Self-expression, all talk and no action, haphazard action',
    description: 'Eager communication and mental curiosity',
    element: 'Air'
  },
  {
    id: 'knight-of-swords',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    keywords: ['action', 'impulsiveness', 'defending beliefs', 'haste'],
    uprightMeaning: 'Ambitious, action-oriented, driven to succeed, fast-thinking',
    reversedMeaning: 'Restless, unfocused, impulsive, burn-out',
    description: 'Swift action and intellectual pursuit',
    element: 'Air'
  },
  {
    id: 'queen-of-swords',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    keywords: ['clear communication', 'independence', 'perception', 'direct'],
    uprightMeaning: 'Independent, unbiased judgement, clear boundaries, direct communication',
    reversedMeaning: 'Overly-critical, cold-hearted, cruel, bitterness',
    description: 'Clear communication and independent thinking',
    element: 'Air'
  },
  {
    id: 'king-of-swords',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    keywords: ['mental clarity', 'authority', 'truth', 'justice'],
    uprightMeaning: 'Mental clarity, intellectual power, authority, truth, justice',
    reversedMeaning: 'Quiet power, inner truth, misuse of power, manipulation',
    description: 'Intellectual authority and clear judgment',
    element: 'Air'
  }
];

export const minorArcanaPentacles: TarotCard[] = [
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    keywords: ['opportunity', 'prosperity', 'new venture', 'manifestation'],
    uprightMeaning: 'New financial opportunity, manifestation, prosperity',
    reversedMeaning: 'Lost opportunity, lack of planning, limited resources',
    description: 'New material or financial opportunity',
    element: 'Earth'
  },
  {
    id: 'two-of-pentacles',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    keywords: ['balance', 'adaptability', 'time management', 'flexibility'],
    uprightMeaning: 'Multiple priorities, time management, adaptability, balance',
    reversedMeaning: 'Over-committed, disorganization, reprioritization',
    description: 'Juggling multiple responsibilities',
    element: 'Earth'
  },
  {
    id: 'three-of-pentacles',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    keywords: ['teamwork', 'collaboration', 'learning', 'implementation'],
    uprightMeaning: 'Teamwork, collaboration, learning, implementation, effort',
    reversedMeaning: 'Disharmony, misalignment, working alone, lack of cohesion',
    description: 'Collaboration and skill development',
    element: 'Earth'
  },
  {
    id: 'four-of-pentacles',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    keywords: ['conservation', 'security', 'frugality', 'control'],
    uprightMeaning: 'Saving money, security, conservatism, frugality, control',
    reversedMeaning: 'Over-spending, greed, self-protection, possessiveness',
    description: 'Holding onto resources and security',
    element: 'Earth'
  },
  {
    id: 'five-of-pentacles',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    keywords: ['hardship', 'loss', 'isolation', 'worry'],
    uprightMeaning: 'Financial loss, poverty, lack mindset, isolation, worry',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty',
    description: 'Material hardship and feeling left out',
    element: 'Earth'
  },
  {
    id: 'six-of-pentacles',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    keywords: ['generosity', 'charity', 'sharing', 'fairness'],
    uprightMeaning: 'Generosity, charity, community, sharing wealth, fairness',
    reversedMeaning: 'Strings attached, stinginess, power and domination',
    description: 'Generosity and sharing resources',
    element: 'Earth'
  },
  {
    id: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    keywords: ['patience', 'investment', 'hard work', 'growth'],
    uprightMeaning: 'Long-term view, sustainable results, perseverance, investment',
    reversedMeaning: 'Lack of long-term vision, limited success, impatience',
    description: 'Patient investment and long-term rewards',
    element: 'Earth'
  },
  {
    id: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
    uprightMeaning: 'Apprenticeship, repetitive tasks, mastery, skill development',
    reversedMeaning: 'Self-development, perfectionism, misdirected activity',
    description: 'Dedication to craft and skill development',
    element: 'Earth'
  },
  {
    id: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
    uprightMeaning: 'Abundance, luxury, self-sufficiency, financial independence',
    reversedMeaning: 'Self-worth, over-investment in work, hustling',
    description: 'Material success and independence',
    element: 'Earth'
  },
  {
    id: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    keywords: ['legacy', 'family', 'inheritance', 'wealth'],
    uprightMeaning: 'Wealth, inheritance, family, establishment, retirement',
    reversedMeaning: 'Financial failure, loneliness, loss',
    description: 'Long-term success and family legacy',
    element: 'Earth'
  },
  {
    id: 'page-of-pentacles',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    keywords: ['manifestation', 'financial opportunity', 'new job', 'skill development'],
    uprightMeaning: 'Manifestation, financial opportunity, new job, skill development',
    reversedMeaning: 'Lack of progress, procrastination, learn from failure',
    description: 'New financial or career opportunity',
    element: 'Earth'
  },
  {
    id: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    keywords: ['efficiency', 'routine', 'conservatism', 'methodical'],
    uprightMeaning: 'Efficiency, hard work, routine, conservatism, methodical',
    reversedMeaning: 'Self-discipline, boredom, feeling stuck, perfectionism',
    description: 'Steady progress and reliability',
    element: 'Earth'
  },
  {
    id: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    keywords: ['practicality', 'creature comforts', 'financial security', 'nurturing'],
    uprightMeaning: 'Nurturing, practical, providing financially, working parent',
    reversedMeaning: 'Financial independence, self-care, work-home conflict',
    description: 'Practical nurturing and abundance',
    element: 'Earth'
  },
  {
    id: 'king-of-pentacles',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    keywords: ['wealth', 'business', 'leadership', 'security'],
    uprightMeaning: 'Wealth, business, leadership, security, discipline, abundance',
    reversedMeaning: 'Financially inept, obsessed with wealth, stubborn',
    description: 'Material mastery and financial success',
    element: 'Earth'
  }
];

export const allMinorArcana = [
  ...minorArcanaWands,
  ...minorArcanaCups,
  ...minorArcanaSwords,
  ...minorArcanaPentacles
];